In [1]:
import pandas as pd

In [5]:
pcc7942 = pd.read_csv('v2_TSS.csv')
pcc7942 = pcc7942[['Start','End','Strand','Mean RNA Seq over ORF']]
pcc7942 = pcc7942.dropna()

In [15]:
pcc7942 = pcc7942.astype({'Start': 'int32', 'End': 'int32', 'Strand': 'int32'})

In [16]:
pcc7942

Start      End  Strand  Mean RNA Seq over ORF
0          65     1237       1              20.027280
1        1262     2134       1               6.840779
2        2178     4511       1              14.314053
3        4596     6077       1              33.618758
4        6111     7706       0               3.380326
...       ...      ...     ...                    ...
2660  2658499  2658574       0               0.000000
2661  2658605  2658681       0               0.000000
2662  2658843  2660332       0               0.000000
2663  2666838  2666924       0           74615.632180
2664  2676606  2676678       0           13661.095890

[2665 rows x 4 columns]

In [17]:
pcc7942['Strand'].unique()

array([1, 0], dtype=int32)

In [20]:
pcc7942.dtypes

Start                      int32
End                        int32
Strand                     int32
Mean RNA Seq over ORF    float64
dtype: object

In [23]:
trlist = []
comp_dic = {'A':'T','G':'C','C':'G','T':'A'}
prolen = 100
# dtypes = {0: 'int', 1: 'int', 2: 'int', 3: 'float'} 
numpydf = pcc7942.to_numpy()
print(numpydf[:10])


[[6.50000000e+01 1.23700000e+03 1.00000000e+00 2.00272805e+01]
 [1.26200000e+03 2.13400000e+03 1.00000000e+00 6.84077892e+00]
 [2.17800000e+03 4.51100000e+03 1.00000000e+00 1.43140531e+01]
 [4.59600000e+03 6.07700000e+03 1.00000000e+00 3.36187584e+01]
 [6.11100000e+03 7.70600000e+03 0.00000000e+00 3.38032581e+00]
 [7.77900000e+03 8.19200000e+03 0.00000000e+00 4.08695652e+00]
 [8.18900000e+03 8.53900000e+03 0.00000000e+00 1.19772080e+01]
 [8.53600000e+03 8.85900000e+03 0.00000000e+00 2.67530864e+01]
 [8.96400000e+03 1.01660000e+04 1.00000000e+00 1.08536991e+01]
 [1.02520000e+04 1.08780000e+04 0.00000000e+00 2.12886762e+01]]


In [25]:
pccgene = []
pccseq = ''

data = open('pcc7942_final_full','r')
lines = data.readlines()
line = [line.strip() for line in lines]
pccseq = ''.join(line)
data.close()
pccseq = pccseq.upper()
print(pccseq[:500])

TTAAAAAAGAGATCCGATCTAGTAATCGCACCGTCAAAAATCCTTGTGGAAGAGCAGTGCTACGATGCTTTGGCAAGATTGCGATCAAAGGCTCGGGCAGCCTCCCCCCATGAAGTTGGTCTGTCGCCAAAACGAACTGAATACCAGTCTGTCGCTCGTTAGCCGTGCTGTACCTTCCCGCCCGAATCATCCGGTGCTTGCCAACGTGCTTCTAGCGGCTGATGCCGGTACTCAACGACTGAGCTTAACCGCCTTTGATCTCAGCCTCGGAATTCAAACCAGCTTTGCCGCGCAAGTCGAACGGAGCGGTGCCATCACTCTACCGGCCAAGCTGCTCAACGATATCGTTTCGCGCCTCCCCAACGACAGCGACGTCACGCTGGAAGACAACGATGCAGCGGCGACTCTGTCAGTGGGGTCTGGCCAGTACCAAATGCGGGGGATCAGTGCCGATGAATTTCCTGAGTTGCCTCTGGTTCAGAGCCAAGAAGCTCTACAAC


In [ ]:
pccseq[:10000]

In [26]:
len(pccseq)

2695903

In [27]:
for i in numpydf:
    # chromosomal DNA
    #positive strands
    if int(i[2]) == 1:
        # pccseq[i[2](TSS) - (prolen+1) (TSS로부터 100bp upstream) : TSS-1] - promoter sequence indexing, i[19]: RNA reads
        if (int(i[0])-(prolen+1)) > 0:
            trlist.append((pccseq[int(i[0])-(prolen+1):int(i[0])-1],i[3]))

    # negative strands
    else:
        compseq = ''
        seq = pccseq[int(i[1]):int(i[1])+prolen]
        for s in seq:
            compseq +=comp_dic[s]
        #역방향으로 complementary seq promoter 추출
        revcomp_seq = compseq[::-1]
        trlist.append((revcomp_seq, i[3]))

In [28]:
trlist

[('CAGCCCTGTCGTGCTCAGTCCGTTGGGACCCGTCAAAATCACCTACTTGGTGATGCCGATTCAGTTGCGCAGCTAGAGTTGAGATCCCCTTTTTCTCACC',
  6.840778923),
 ('CCAGCACAGCCCCTGATTCCGCCCGAGGCTTGGGACGACGACGACCCGTGGGTCTAACGCCGATACAATTAAGGACGACTTCTGCGGGAATTCCAAAGCC',
  14.31405313),
 ('TTTGGCTAAAGACTAACCGCTAGGGTTAAGTCATTGTTAAATTTGCATTAGCCGCTACAACGCTGGCCATCTTTTTGCCAATCAGGAGCTCTGCAAGGGC',
  33.61875843),
 ('TTCTGTACCAGATTCAAAAGATCGTTAGCGCAGACGCTGCAGTTCTCAGCACTTGCCAGCAGAATGAGCGGCAGTGTTTGTCGTTGCGCTCTCAATCCTG',
  3.380325815),
 ('GATCGGGTGTGGCGGCAGCCAAACAGGAATGGCAAACGACGACGATCGCGGCGGAATCCGTCAGTGAGCATGAGTCCTCTAGCCCCGATCAGTCGGCCTC',
  4.086956522),
 ('GGCAACTGTGGCAGCAGTGGCAACTGTTGCTGAAATTTCTGGGACTCTTGCAGCCGTGGGTTCCTCTGTTCACCCCACCGAAAAAGTCTCGGGCAGCCCA',
  11.97720798),
 ('ATCCACTCCGCTGTTGAAACAGCCTTTTATTATCGCAGTTTGCCTGCGGTCTCAGAAGAAGGTCGCTATCATTGCAGGGAGCATTTTTGAGCCTTCGGCT',
  26.75308642),
 ('GAAGGCTCAAAAATGCTCCCTGCAATGATAGCGACCTTCTTCTGAGACCGCAGGCAAACTGCGATAATAAAAGGCTGTTTCAACAGCGGAGTGGATTGTC',
  10.85369909),
 ('TCGGTAGCACTCCTCGACAGC

In [29]:
final_list = []

In [30]:
for i in range(len(trlist)):
    final_list.append(trlist[i][0])

In [31]:
df = pd.DataFrame(final_list)
df

0
0     CAGCCCTGTCGTGCTCAGTCCGTTGGGACCCGTCAAAATCACCTAC...
1     CCAGCACAGCCCCTGATTCCGCCCGAGGCTTGGGACGACGACGACC...
2     TTTGGCTAAAGACTAACCGCTAGGGTTAAGTCATTGTTAAATTTGC...
3     TTCTGTACCAGATTCAAAAGATCGTTAGCGCAGACGCTGCAGTTCT...
4     GATCGGGTGTGGCGGCAGCCAAACAGGAATGGCAAACGACGACGAT...
...                                                 ...
2659  TAGCTCAGGTGGTTAGAGCGCACCCCTGATAAGGGTGAGGTCCCTG...
2660  ATCAGAGGTCAACCTAGGTCGGTCGAGTCTTTCGAGCAAGGGCTTC...
2661  ACTCGTCAATAAAATGATGAATCCGGTTAACTGGGTTCGGGAAAAC...
2662  CGCTCATGCGGGGTTCCCGGCAGCCAACTGCTGTTTTGACCGAAGT...
2663  GGCGCTGCAGGCGTGACATTGGCGATCGCGGGTCAACTTGGCCCAA...

[2664 rows x 1 columns]

In [32]:
df.to_csv('final_7942promoter.csv', index = False)