In [1]:
import pandas as pd

In [2]:
transcript = pd.read_csv('TSSdata_for7942.csv')
noncoding = pd.read_csv('noncodingTSS_for7942.csv')

In [3]:
transcript

Strand   5' TSS   3' End  Mean RNA sequencing over transcript
0          0   235367   232565                            23.493400
1          0   301482   299962                             2.667982
2          0  1046366  1045940                             5.946136
3          0  1452478  1451255                             5.293301
4          0  1886374  1884286                            90.260890
...      ...      ...      ...                                  ...
1468       0   259201   258566                             7.658805
1469       0  2142258  2141852                             4.304668
1470       1   546531   548062                            12.899478
1471       1   791060   791726                             4.025487
1472       1  2169842  2173272                             9.171087

[1473 rows x 4 columns]

In [4]:
noncoding

Strand       5'       3'  Mean RNA Sequencing over non-coding transcript
0          1     8071     8230                                        2.331250
1          1    10912    11082                                       12.187135
2          1    11813    12140                                        2.304878
3          1    13058    13598                                        5.842884
4          1    14060    15005                                        7.651163
...      ...      ...      ...                                             ...
1574       0  2676604  2676100                                       43.530693
1575       0  2678800  2678266                                        6.968224
1576       0  2679900  2679700                                        2.238806
1577       0  2691100  2690989                                        4.580357
1578       0  2692000  2691300                                        3.512126

[1579 rows x 4 columns]

### Transcript

In [7]:
transcript['Strand'].unique()

array([0, 1])

In [12]:
transcript.dtypes

Strand                                   int64
5' TSS                                   int64
3' End                                   int64
Mean RNA sequencing over transcript    float64
dtype: object

In [20]:
trlist = []
comp_dic = {'A':'T','G':'C','C':'G','T':'A'}
prolen = 100 
numpydf = transcript.to_numpy(dtype = 'int32')
print(numpydf[:10])


[[      0  235367  232565      23]
 [      0  301482  299962       2]
 [      0 1046366 1045940       5]
 [      0 1452478 1451255       5]
 [      0 1886374 1884286      90]
 [      0 2388599 2386163       7]
 [      1  121282  121353   17805]
 [      1  123940  124014     142]
 [      1  152497  154953       4]
 [      1  316991  318015       3]]


In [21]:
pccgene = []
pccseq = ''

data = open('pcc7942_final_full','r')
lines = data.readlines()
line = [line.strip() for line in lines]
pccseq = ''.join(line)
data.close()
pccseq = pccseq.upper()
print(pccseq[:500])

TTAAAAAAGAGATCCGATCTAGTAATCGCACCGTCAAAAATCCTTGTGGAAGAGCAGTGCTACGATGCTTTGGCAAGATTGCGATCAAAGGCTCGGGCAGCCTCCCCCCATGAAGTTGGTCTGTCGCCAAAACGAACTGAATACCAGTCTGTCGCTCGTTAGCCGTGCTGTACCTTCCCGCCCGAATCATCCGGTGCTTGCCAACGTGCTTCTAGCGGCTGATGCCGGTACTCAACGACTGAGCTTAACCGCCTTTGATCTCAGCCTCGGAATTCAAACCAGCTTTGCCGCGCAAGTCGAACGGAGCGGTGCCATCACTCTACCGGCCAAGCTGCTCAACGATATCGTTTCGCGCCTCCCCAACGACAGCGACGTCACGCTGGAAGACAACGATGCAGCGGCGACTCTGTCAGTGGGGTCTGGCCAGTACCAAATGCGGGGGATCAGTGCCGATGAATTTCCTGAGTTGCCTCTGGTTCAGAGCCAAGAAGCTCTACAAC


In [22]:
len(pccseq)

2695903

In [23]:
for i in numpydf:
    # chromosomal DNA
    #positive strands
    if int(i[0]) == 1:
        # pccseq[i[2](TSS) - (prolen+1) (TSS로부터 100bp upstream) : TSS-1] - promoter sequence indexing, i[19]: RNA reads
        if (int(i[1])-(prolen+1)) > 0:
            trlist.append((pccseq[int(i[1])-(prolen+1):int(i[1])-1],i[3]))

    # negative strands
    else:
        compseq = ''
        seq = pccseq[int(i[1]):int(i[1])+prolen]
        for s in seq:
            compseq +=comp_dic[s]
        #역방향으로 complementary seq promoter 추출
        revcomp_seq = compseq[::-1]
        trlist.append((revcomp_seq, i[3]))

In [24]:
trlist

[('TCCTGACTTCTATTGTCAGTCGCCAGAGGTTTGTTGTTAAACGTTACAAGCCTCTCAGGACTTGTTCGGGAGCGCCCCTCCAGTCGCTACACTACTCAAC',
  23),
 ('GTTCTAGTCGGAGTCGGTCAATCGGAACTGTATCCAGCACAGCGATCGTCCCAGGCTGAGCTAAAGCTGGGCTTAAATCTCCTCTCAGGTGCCATTCATC',
  2),
 ('AATCGCTCAGAGTCCACTTCTGTAGTTCGGGATACGGCAAGATAAACTTTTGGATTTGGTTAAGGTGCGATCGCTAGAAGGTCGTAGCAGTATCTCTGCT',
  5),
 ('ATTAATTCAGAACACCCTAACTCACGAGTGCTGGCAATGGTTTGAACGTTGAAAGATCAACCCAAATCAAACCTCCAGTCAAACTTTTAAAAAATAAATT',
  5),
 ('CGATCGCAGTTCACTACTCGCTACTGCAACAACAGAGCGGACGGAAATCCGAACTTTTCCCGACCTGCGCGGCTAGTGCAGGCTCTCCTATGATCAAGCC',
  90),
 ('ACTGCGCGATCGCTTAACGCTTGCGGGGAGATCTGGACTCAGGCGGGATGCTGCTGAGCGATCGTAGATAGACGCCTCTCCGCTGGCTCCCTAGGATAGG',
  7),
 ('GGATGCGGATCGCAATCTGATCTTCGCCGTGACCGTTGCTAAGACAGAGCAAGCGCATACCGTTGTTCGAAAGTCTCTGCTAGAGTAGTGGACTGTGCCT',
  17805),
 ('AAATGCGGATCGCAATCTGATCTTCGCCATGACCGTTGCTGAGACAGAGCAAGCGCATACCGTTGTTCGAAAGTCTCTGGTAGAGGAGTGAGCTTTGCTT',
  142),
 ('TGAGTCAGCCTGTGGAAGCCATCAGCAGAGTGTAAAAGTCCATTGGTCAACAAAATTTCCCTCAGCAATTCTATGAATCTCCTCTAGACCAAG

In [25]:
final_list = []

In [26]:
for i in range(len(trlist)):
    final_list.append(trlist[i][0])

In [27]:
df = pd.DataFrame(final_list)
df

0
0     TCCTGACTTCTATTGTCAGTCGCCAGAGGTTTGTTGTTAAACGTTA...
1     GTTCTAGTCGGAGTCGGTCAATCGGAACTGTATCCAGCACAGCGAT...
2     AATCGCTCAGAGTCCACTTCTGTAGTTCGGGATACGGCAAGATAAA...
3     ATTAATTCAGAACACCCTAACTCACGAGTGCTGGCAATGGTTTGAA...
4     CGATCGCAGTTCACTACTCGCTACTGCAACAACAGAGCGGACGGAA...
...                                                 ...
1467  AGTTGGAGGGGCGATCGGTCCCAAACAAAGCCGGATACTGAGGATT...
1468  CTGGTGCGGGTCCAGAAGTGCTGTTAGCGGCGCTGGAGCAAGTGTC...
1469  GAAGATGGTCGCCTTGTGAAAGGTGGACTGACCAGCCCTGTGCTCC...
1470  AAGCTTGGAAGTCTCGCAGCTCCTGGTCGAGGCTGGTATCACTCCC...
1471  TCAGCAATCTGGAATTGCTGCGGCAGGAGCTAGTCCTCATCCAGCA...

[1472 rows x 1 columns]

In [28]:
df.to_csv('final_7942promoter.csv', index = False)

### noncoding

In [29]:
noncoding['Strand'].unique()

array([1, 0])

In [30]:
noncoding.dtypes

Strand                                              int64
5'                                                  int64
3'                                                  int64
Mean RNA Sequencing over non-coding transcript    float64
dtype: object

In [33]:
trlist_n = []
comp_dic = {'A':'T','G':'C','C':'G','T':'A'}
prolen = 100 
numpydf_n = noncoding.to_numpy(dtype = 'int32')
print(numpydf_n[:10])


[[    1  8071  8230     2]
 [    1 10912 11082    12]
 [    1 11813 12140     2]
 [    1 13058 13598     5]
 [    1 14060 15005     7]
 [    1 17434 17461     5]
 [    1 22539 22812     2]
 [    1 29805 29859     5]
 [    1 33889 34965    26]
 [    1 44666 45000     3]]


In [34]:
pccgene = []
pccseq = ''

data = open('pcc7942_final_full','r')
lines = data.readlines()
line = [line.strip() for line in lines]
pccseq = ''.join(line)
data.close()
pccseq = pccseq.upper()
print(pccseq[:500])

TTAAAAAAGAGATCCGATCTAGTAATCGCACCGTCAAAAATCCTTGTGGAAGAGCAGTGCTACGATGCTTTGGCAAGATTGCGATCAAAGGCTCGGGCAGCCTCCCCCCATGAAGTTGGTCTGTCGCCAAAACGAACTGAATACCAGTCTGTCGCTCGTTAGCCGTGCTGTACCTTCCCGCCCGAATCATCCGGTGCTTGCCAACGTGCTTCTAGCGGCTGATGCCGGTACTCAACGACTGAGCTTAACCGCCTTTGATCTCAGCCTCGGAATTCAAACCAGCTTTGCCGCGCAAGTCGAACGGAGCGGTGCCATCACTCTACCGGCCAAGCTGCTCAACGATATCGTTTCGCGCCTCCCCAACGACAGCGACGTCACGCTGGAAGACAACGATGCAGCGGCGACTCTGTCAGTGGGGTCTGGCCAGTACCAAATGCGGGGGATCAGTGCCGATGAATTTCCTGAGTTGCCTCTGGTTCAGAGCCAAGAAGCTCTACAAC


In [35]:
len(pccseq)

2695903

In [36]:
for i in numpydf_n:
    # chromosomal DNA
    #positive strands
    if int(i[0]) == 1:
        # pccseq[i[2](TSS) - (prolen+1) (TSS로부터 100bp upstream) : TSS-1] - promoter sequence indexing, i[19]: RNA reads
        if (int(i[1])-(prolen+1)) > 0:
            trlist_n.append((pccseq[int(i[1])-(prolen+1):int(i[1])-1],i[3]))

    # negative strands
    else:
        compseq = ''
        seq = pccseq[int(i[1]):int(i[1])+prolen]
        for s in seq:
            compseq +=comp_dic[s]
        #역방향으로 complementary seq promoter 추출
        revcomp_seq = compseq[::-1]
        trlist_n.append((revcomp_seq, i[3]))

In [37]:
trlist_n

[('GCTTTCACTCATCTCATCCGTTAGCTCACTCACTTCTAGGCCAGTCAGCCGCATGGCTTCTAGCGTTGGTGGCAGTTCACGGGAGAGCATATCCAACAGG',
  2),
 ('CATAACCGAAGCGGTGGGCTAGGTCTTGGACCGTTTCTAAGGAGAACAATTCCAAAGGCATGGACATCTCTGCGATCGCATGGCCTAGATCGTAACGGAC',
  12),
 ('ACTTAACCGCAGTGCACGCTCCAACGGGGCAATCTGCGAGCCGTCGCCGGTGTAGTTGATTTGGACGTAGATGCCTTCGCGCTGTTTATTAATCAAGTAG',
  2),
 ('CAGCCCTAAGTGCAGTGATTGAAGTCCCGGTCACCCCGAGCCAATTGCTGGCCATGCTGCCCGATCAATAGCTGATCAACCTGCAGTGGCTCTGGTAAGA',
  5),
 ('CATGGCGACCATACTCCATGCCAGGTTCATAGCGACTAAACAACAGGCTGTGAACACGCTGGGGATAGGCTGCTGCCTCAAAGAGGGCATTATTCTGTAG',
  7),
 ('GAGCGGCTGCTTGCTATCGGTGCGATAGAAGTACTCCCCATCTGCTAACCGCGCCCGAATTACGCGGGCATTGCCAGCAGCAATCGTCTCACTGGCCGCC',
  5),
 ('CTGAGGACAGCAGCTGTCCGACCTTCTGCCAGCATTCGTTCCAGCGGCCAGTCTTCGAGCAGTCCTTCTTCATCGCTAATCAGATCTGAGATGCCCTGAA',
  2),
 ('TCTATCGCCAGTGCTATCGACCGCAAACTGCGCCGGAATTACCGGCGATCGCCCCCGATCGCGATCGCTTGTTGGCAGATTTGGAACAGCTCGATCGCAG',
  5),
 ('TGGGATGTAACTCTTCTGTTCCGAGTTCATAAAAGAATCTGACTCCTAAAGAGAATCTAAAAAAATCAAGGTTGTCAGTAGTTGAAATCTTATTCTACTA

In [38]:
final_list_n = []

In [39]:
for i in range(len(trlist_n)):
    final_list_n.append(trlist_n[i][0])

In [40]:
df_n = pd.DataFrame(final_list_n)
df_n

0
0     GCTTTCACTCATCTCATCCGTTAGCTCACTCACTTCTAGGCCAGTC...
1     CATAACCGAAGCGGTGGGCTAGGTCTTGGACCGTTTCTAAGGAGAA...
2     ACTTAACCGCAGTGCACGCTCCAACGGGGCAATCTGCGAGCCGTCG...
3     CAGCCCTAAGTGCAGTGATTGAAGTCCCGGTCACCCCGAGCCAATT...
4     CATGGCGACCATACTCCATGCCAGGTTCATAGCGACTAAACAACAG...
...                                                 ...
1574  TGACCGCTAGTATGGTAGCGAAATCTCCAGGGTTGGCCGAGCGGAT...
1575  TTGACCCGCTTGCTGAGGGCTTGCGCAGCAGCTGCACTCATCCCAG...
1576  CCCCCAAAGATCCCTGACGCCAACCATCACCCTGGACGAGAAACTT...
1577  TGCCGCTGCCAACGGGAGCAAACTGCGCCTGAGCAAAGGGAGCAAC...
1578  GAGCAATCAACCCCAGTAGCGAATCCACATTGACCCGCATGTTGGT...

[1579 rows x 1 columns]

In [41]:
df_n.to_csv('final_7942promoter_noncoding.csv', index = False)